#!/bin/bash
pip3 install numpy python-dev-tools
apt install cmake gcc g++ libavcodec-dev libavformat-dev libswscale-dev libgstreamer-plugins-base1.0-dev 
apt install libgstreamer1.0-dev libgtk2.0-dev libgtk-3-dev libpng-dev libjpeg-dev libopenexr-dev libtiff-dev libwebp-dev

cd opencv/build
make install
